In [1]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
b = np.zeros([3, 0, 2, 5])
b

array([], shape=(3, 0, 2, 5), dtype=float64)

In [16]:
c = np.arange(12).reshape((3, 4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
print(c[[1, 2], [0,2]])

[ 4 10]


In [36]:
e = np.arange(6)
print(e.T)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
a

array([[1., 2., 1.],
       [1., 1., 4.],
       [2., 3., 6.]], dtype=float32)

In [41]:
det = np.linalg.det(a)
det

-1.0

In [42]:
print(a)
print(det)

[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
-1.0


In [44]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)
r

2

In [51]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])
m

array([[1, 2, 3],
       [1, 1, 1],
       [2, 3, 5]])

In [52]:
print(np.linalg.matrix_rank(m), m.shape)

3 (3, 3)


In [59]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])

print(a)
print(b)

x, res, r, s = np.linalg.lstsq(a, b, rcond=None)
a.dot(x)

[[0 1]
 [1 1]
 [2 1]
 [3 1]]
[-1.   0.2  0.9  2.1]


array([-0.95,  0.05,  1.05,  2.05])

In [63]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=int)
b = np.linalg.inv(a)
print(a)
print(b)

print(a*b)
print(a.dot(b))

[[1 2 1]
 [1 1 4]
 [2 3 6]]
[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
[[ 6. 18. -7.]
 [-2. -4. 12.]
 [-2. -3.  6.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(a)
print(w)
print(v)

print(v[:, 1], '==', w[1])

[[-1 -6]
 [ 2  6]]
[2. 3.]
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]
[ 0.83205029 -0.5547002 ] == 3.0


In [75]:
e = np.ones((4, 5))
e = np.eye(4, 5)
print(e)
e[[0, 3], [1, 3]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


array([0., 1.])