## Cross Validation

In [1]:
from sklearn import model_selection, datasets
import numpy as np

### Разбиение данных на обучение и тест

In [2]:
iris = datasets.load_iris()

train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target,
                                                                                    test_size=0.3)


In [7]:
print(f'Размер обучающей выборки: {len(train_data)} объектов,'
      f'\nРазмер тестовой выборки: {len(test_data)} объектов')

Размер обучающей выборки: 105 объектов,
Размер тестовой выборки: 45 объектов


### Кросс валидация

In [12]:
X = range(100, 110)

#### KFold - поделить на части

In [18]:
kf = model_selection.KFold(n_splits=2, shuffle=True, random_state=1)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold - сохранить распределение классов

In [42]:
y = np.array([0, 1] * 5)
print(y)

skf = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=0)
for train_indices, test_indices in skf.split(X, y):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[0 3 6 7 8 9] [1 2 4 5]
[1 2 4 5 7 8 9] [0 3 6]
[0 1 2 3 4 5 6] [7 8 9]


#### ShuffleSplit - много тестов

In [46]:
ss = model_selection.ShuffleSplit(n_splits=10, test_size=0.2, random_state=1)
for train_indices, test_indices in ss.split(X):
    print(train_indices, test_indices)

[6 4 0 3 1 7 8 5] [2 9]
[3 0 8 4 2 1 6 7] [9 5]
[5 9 0 6 1 7 4 2] [8 3]
[3 0 6 1 5 8 7 9] [2 4]
[7 0 1 2 3 5 9 8] [6 4]
[4 0 9 8 1 5 6 3] [2 7]
[8 6 2 1 3 5 0 4] [7 9]
[5 6 0 1 8 7 2 9] [4 3]
[2 8 1 3 4 5 9 7] [6 0]
[5 7 4 3 1 8 2 0] [6 9]


In [47]:
target = np.array([0] * 5 + [1] * 5)

ss = model_selection.StratifiedShuffleSplit(n_splits=4, test_size=0.2, random_state=1)
for train_indices, test_indices in ss.split(X, target):
    print(train_indices, test_indices)


[4 9 7 0 5 1 8 2] [6 3]
[4 8 3 2 5 0 9 6] [1 7]
[2 1 5 9 7 4 8 3] [0 6]
[6 2 8 0 9 4 7 1] [5 3]


#### Leave-One-Out

In [48]:
loo = model_selection.LeaveOneOut()
for train_indices, test_indices in loo.split(X):
    print(train_indices, test_indices)


[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
